# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
    # The branches below must be a subset of the branches above
  #  branches: [ "master" ]
  #schedule:
  #  - cron: '43 4 * * 1'
  workflow_dispatch:

jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  build-and-pipeline-scan:
    # The type of runner that the job will run on
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      issues: write 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and copies all sources into ZIP file for submitting for analysis. Replace this section with your applications build steps
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0

    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: adopt

    - name: Build Java
      run: |
       javac -verbose -g -cp ".:./lib/commons-codec-1.5.jar:./lib/commons-lang-2.5.jar:./lib/javamail-1.4.4.jar:./lib/servlet-api.jar" ./src/testcasesupport/IO.java ./src/testcasesupport/AbstractTestCaseBase.java ./src/testcasesupport/AbstractTestCase.java ./src/testcasesupport/AbstractTestCaseBadOnly.java ./src/testcasesupport/AbstractTestCaseServletBase.java ./src/testcasesupport/AbstractTestCaseServlet.java ./src/testcasesupport/AbstractTestCaseServletBadOnly.java ./src/testcasesupport/AbstractTestCaseClassIssue.java ./src/testcasesupport/AbstractTestCaseClassIssueBad.java ./src/testcasesupport/AbstractTestCaseClassIssueGood.java ./src/testcases/CWE89_SQL_Injection/*.java

    - name: Run Veracode SCA
      env:
        SRCCLR_API_TOKEN: ${{ secrets.VERACODE_API_TOKEN  }}
      #run: curl -sSL https://download.sourceclear.com/ci.sh | sh
      #run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan ./src/testcases/CWE89_SQL_Injection --recursive --debug
      uses: veracode/veracode-sca@v2.0.65
      with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ github.token }}
        create-issues: true
        debug: true
        path: ./src/testcases/CWE89_SQL_Injection
        recursive: true

#    - name: Veracode Upload And Scan
#      uses: veracode/veracode-uploadandscan-action@0.2.4
#      with:
#        # For more info visit: https://github.com/marketplace/actions/veracode-upload-and-scan
#        appname: '${{ secrets.VERACODE_APP_NAME }}'
#        sandboxname: '${{ secrets.VERACODE_SANDBOX_NAME }}'
#        version: '${{ github.ref_name }}-${{ github.run_id }}'
#        createprofile: false
#        filepath: './src/testcases/CWE89_SQL_Injection/*.class'
#        vid: '${{ secrets.VERACODE_API_ID }}'
#        vkey: '${{ secrets.VERACODE_API_KEY }}'
##          createsandbox: 'true'
##          scantimeout: 0
##          exclude: '*.js'
##          include: '*.jar'
##          criticality: 'VeryHigh'
